# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

# Function to include common pods for all targets
def common_pods(target_name)
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

end

# ✅ Apply common_pods to each target
target 'HighlandApp' do
  common_pods('HighlandApp')
end

target 'Highland DEV' do
  common_pods('Highland DEV')
end

target 'Highland UAT' do
  common_pods('Highland UAT')
end

# ✅ Define a single `post_install` hook for all targets
post_install do |installer|
  react_native_post_install(
    installer,
    use_native_modules![:reactNativePath],
    :mac_catalyst_enabled => false
  )
end